# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cExZtEMnLyGBbv8gL_W02J32IeGB19-F
"""

import numpy as nupy
arr = nupy.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
newarray = arr.reshape(2,5,2)
print(newarray)