# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NsZ96l10sB3twa9-oZpDhtPDo9RgVPYn
"""

import numpy as np
from numpy import random
arr= random.randint(100,size=(5,10))
print(np.sort(arr))